### ISSUE TITLE
Website doesn't load if prefixed with www

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/idem-website#16]
If you have a www at the start( which browsers like to automatically add), the website doesn't load. Update DNS to make sure all the following work:
idem.com.au
www.idem.com.au
http://idem.com.au
http://www.idem.com.au
https://idem.com.au
https://www.idem.com.au

**Comment by JasminFarhi** [comment]
Takes 48hrs to work https://docs.digitalocean.com/products/networking/dns/how-to/manage-records/#:~:text=These%20records%20will%20not%20take,take%20up%20to%2048%20hours.

**Comment by brettvniekerk** [comment]
Added domain to DO app, and added CNAME alias to domain storage
