### ISSUE TITLE
As IDEM I want to implement the given designs for the IDEM website so users understand the IDEM brand

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-website#6]
## Context
Create the idem website based off the designs given from @bitcoinbrisbane 

New desgins: 
https://www.figma.com/file/AXY6gQrbdGTUVgHzt9wtYT/IDEM-Mini-Landing-Page?node-id=0%3A1

To be completed: 
just the first page of the Figma, no need for nav or page down at this stage. 

Please visit the URL - https://idem.com.au/ 
For Tesing

**Comment by Mitchell139** [comment]
Only one of the "pages" have been created 
![image](https://user-images.githubusercontent.com/50130291/178441115-fe46164b-29b0-4cce-acb4-99ffba8f0b61.png)

**Comment by bitcoinbrisbane** [comment]
> Only one of the "pages" have been created ![image](https://user-images.githubusercontent.com/50130291/178441115-fe46164b-29b0-4cce-acb4-99ffba8f0b61.png)

One page is fine.  We can remove other links?

**Comment by Mitchell139** [comment]
Is this suppose to be hosted somewhere?



These should be in bold 
![image](https://user-images.githubusercontent.com/50130291/178893261-426cf970-e27e-4691-9fd7-d89b72a1466b.png)




Background doesn't fill the... background depending on screen size
![image](https://user-images.githubusercontent.com/50130291/178893405-d545e2eb-d386-480c-ae73-5d6d4bf11b75.png)
![image](https://user-images.githubusercontent.com/50130291/178893457-1c579dba-435d-4319-a549-c0291b6d76a6.png)

**Comment by C00p3rb123** [comment]
**As the per the figma:**

- Green Circle: This should be centred on x and y axis, currently centred on the x axis but appearing at the top the page.

- Red Circle: Font needs to be slightly bigger

- Background still not filling the background depending on size

<img width="1834" alt="image" src="https://user-images.githubusercontent.com/48899363/179433988-73d03244-07f7-45d6-8ae7-f60fb8cb186d.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/48899363/179434113-4012795d-b749-4043-9c04-9e9ee4780fe9.png">

**Comment by Mitchell139** [comment]
@JasminFarhi Please add the url of where the site is hosted

**Comment by Mitchell139** [comment]
Background image doesn't fill background
![image](https://user-images.githubusercontent.com/50130291/179889908-b4cfd3bc-4f21-4394-954b-1a19fb2e4b22.png)



Should be easy to fix these console errors 
![image](https://user-images.githubusercontent.com/50130291/179890178-cf64f4c3-709d-4ff8-a7ae-ef3eb981e1e0.png)



Title not set/working 
![image](https://user-images.githubusercontent.com/50130291/179890223-8f99cd6b-299f-4468-9c21-6e95acdd6210.png)
